# Generated by Django 4.2.23 on 2025-07-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0002_ipresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='temps_limite',
            field=models.PositiveIntegerField(blank=True, help_text='Durée limite en minutes pour cette question', null=True),
        ),
        migrations.AddField(
            model_name='tentative',
            name='temps_limite',
            field=models.PositiveIntegerField(blank=True, help_text='Durée limite en minutes pour cette tentative', null=True),
        ),
    ]
