# Generated by Django 4.2.23 on 2025-07-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0003_question_temps_limite_tentative_temps_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('vrai_faux', 'Vrai/Faux'), ('texte_court', 'Texte court'), ('texte_long', 'Texte long')], default='choix_unique', max_length=20),
        ),
        migrations.AddField(
            model_name='reponsetentative',
            name='texte_reponse',
            field=models.TextField(blank=True, help_text='Réponse libre pour les questions texte', null=True),
        ),
        migrations.AlterField(
            model_name='reponsetentative',
            name='choix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prepaconcours.choix'),
        ),
    ]
