# Generated by Django 4.2.23 on 2025-07-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0004_question_type_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correction_mode',
            field=models.CharField(blank=True, choices=[('exacte', 'Exacte'), ('mot_cle', 'Mot-clé'), ('regex', 'Regex')], default='exacte', help_text='Mode de correction automatique pour les questions texte', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='reponse_attendue',
            field=models.TextField(blank=True, help_text='Pour les questions texte : réponse attendue, mot-clé ou regex', null=True),
        ),
    ]
