# Generated by Django 4.2.23 on 2025-07-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0005_question_correction_mode_question_reponse_attendue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='est_admin',
            new_name='is_admin',
        ),
    ]
