# Generated by Django 4.2.23 on 2025-07-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0006_rename_est_admin_to_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='est_actif',
            new_name='is_active',
        ),
    ]
