# Generated by Django 4.2.23 on 2025-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0007_rename_est_actif_to_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='choix',
            name='explication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
