# Generated by Django 4.2.23 on 2025-07-13 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0008_choix_explication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importexcel',
            options={'ordering': ['-date_import'], 'verbose_name': 'Import Excel', 'verbose_name_plural': 'Imports Excel'},
        ),
        migrations.RemoveField(
            model_name='importexcel',
            name='nombre_questions_importees',
        ),
        migrations.AddField(
            model_name='importexcel',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='importexcel',
            name='details',
            field=models.JSONField(blank=True, help_text="Détails supplémentaires sur l'import", null=True),
        ),
        migrations.AddField(
            model_name='importexcel',
            name='erreur',
            field=models.TextField(blank=True, null=True, verbose_name="Message d'erreur"),
        ),
        migrations.AddField(
            model_name='importexcel',
            name='import_type',
            field=models.CharField(choices=[('questions', 'Questions'), ('matieres', 'Matières'), ('utilisateurs', 'Utilisateurs')], default='questions', max_length=20, verbose_name="Type d'import"),
        ),
        migrations.AddField(
            model_name='importexcel',
            name='nombre_echecs',
            field=models.PositiveIntegerField(default=0, verbose_name='Échecs'),
        ),
        migrations.AddField(
            model_name='importexcel',
            name='nombre_elements_importes',
            field=models.PositiveIntegerField(default=0, verbose_name='Éléments importés'),
        ),
        migrations.AddField(
            model_name='importexcel',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='importexcel',
            name='date_import',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'import"),
        ),
        migrations.AlterField(
            model_name='importexcel',
            name='fichier_nom',
            field=models.CharField(max_length=255, verbose_name='Nom du fichier'),
        ),
    ]
