# Generated by Django 4.2.23 on 2025-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0009_alter_importexcel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='temps_limite',
            field=models.PositiveIntegerField(blank=True, help_text='Durée limite en secondes pour répondre à cette question (laisser vide pour la valeur par défaut)', null=True),
        ),
    ]
