# Generated by Django 4.2.23 on 2025-07-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0010_alter_question_temps_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentative',
            name='terminee',
            field=models.BooleanField(default=False),
        ),
    ]
