# Generated by Django 4.2.23 on 2025-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0012_sessionquiz_tentative_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionquiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='prepaconcours.question'),
        ),
    ]
