# Generated by Django 4.2.23 on 2025-07-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0013_sessionquiz_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionquiz',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_quiz', to='prepaconcours.matiere'),
        ),
    ]
