# Generated by Django 4.2.23 on 2025-07-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0014_sessionquiz_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choix_concours',
            field=models.CharField(choices=[('ENA', 'ENA'), ('fonction_publique', 'Fonction Publique')], default='ENA', max_length=32),
        ),
        migrations.AddField(
            model_name='sessionquiz',
            name='choix_concours',
            field=models.CharField(choices=[('ENA', 'ENA'), ('fonction_publique', 'Fonction Publique')], default='ENA', max_length=32),
        ),
        migrations.AddField(
            model_name='tentative',
            name='choix_concours',
            field=models.CharField(choices=[('ENA', 'ENA'), ('fonction_publique', 'Fonction Publique')], default='ENA', max_length=32),
        ),
        migrations.AddField(
            model_name='tentative',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentatives', to='prepaconcours.cycle'),
        ),
        migrations.AlterField(
            model_name='sessionquiz',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_quiz', to='prepaconcours.cycle'),
        ),
    ]
