# Generated by Django 4.2.23 on 2025-07-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0015_question_choix_concours_sessionquiz_choix_concours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='prepaconcours.cycle'),
        ),
    ]
