# Generated by Django 4.2.23 on 2025-07-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0016_alter_matiere_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='choix_concours',
            field=models.CharField(choices=[('ENA', 'ENA'), ('fonction_publique', 'Fonction Publique')], default='ENA', max_length=20),
        ),
    ]
