# Generated by Django 4.2.23 on 2025-07-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0017_matiere_choix_concours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'cycle', 'choix_concours')},
        ),
    ]
