# Generated by Django 4.2.23 on 2025-08-01 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0018_alter_matiere_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='sessionquiz',
            name='niveau',
        ),
        migrations.AddField(
            model_name='matiere',
            name='tour_ena',
            field=models.CharField(blank=True, choices=[('premier_tour', 'Premier Tour'), ('second_tour', 'Second Tour'), ('oral', 'Oral')], help_text="Tour ENA (uniquement pour choix_concours='ENA')", max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'cycle', 'choix_concours', 'tour_ena')},
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_contenu', models.CharField(choices=[('quiz', 'Quiz'), ('pdf', 'PDF'), ('video', 'Vidéo'), ('zoom', 'Session Zoom Live')], default='quiz', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, help_text='Fichier PDF pour les leçons de type PDF', null=True, upload_to='lecons/pdf/')),
                ('url_video', models.URLField(blank=True, help_text='URL de la vidéo pour les leçons de type vidéo', null=True)),
                ('url_zoom', models.URLField(blank=True, help_text='Lien Zoom pour les sessions live', null=True)),
                ('date_session_zoom', models.DateTimeField(blank=True, help_text='Date et heure de la session Zoom', null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la matière")),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='prepaconcours.matiere')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
                'unique_together': {('nom', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='lecon',
            field=models.ForeignKey(blank=True, help_text='Leçon à laquelle appartient cette question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='prepaconcours.lecon'),
        ),
        migrations.AddField(
            model_name='sessionquiz',
            name='lecon',
            field=models.ForeignKey(blank=True, help_text='Leçon pour cette session de quiz', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_quiz', to='prepaconcours.lecon'),
        ),
    ]
