# Generated by Django 4.2.23 on 2025-08-01 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0019_alter_matiere_unique_together_remove_question_niveau_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecon',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Leçon (Catégorie)', 'verbose_name_plural': 'Leçons (Catégories)'},
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='date_session_zoom',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='fichier_pdf',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='type_contenu',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='url_video',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='url_zoom',
        ),
        migrations.AlterField(
            model_name='lecon',
            name='description',
            field=models.TextField(blank=True, help_text='Description de cette catégorie de leçon', null=True),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='nom',
            field=models.CharField(help_text='Nom de la catégorie (ex: Sport, Éducation, Science)', max_length=200),
        ),
        migrations.CreateModel(
            name='SessionZoomLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la session', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_zoom', models.URLField(help_text='Lien Zoom pour rejoindre la session')),
                ('meeting_id', models.CharField(blank=True, help_text='ID de la réunion Zoom', max_length=50, null=True)),
                ('mot_de_passe', models.CharField(blank=True, help_text='Mot de passe Zoom', max_length=50, null=True)),
                ('date_session', models.DateTimeField(help_text='Date et heure de la session')),
                ('duree_minutes', models.PositiveIntegerField(default=60, help_text='Durée prévue en minutes')),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='programmee', max_length=20)),
                ('nombre_participants_max', models.PositiveIntegerField(default=50, help_text='Nombre maximum de participants')),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_zoom', to='prepaconcours.matiere')),
            ],
            options={
                'verbose_name': 'Session Zoom Live',
                'verbose_name_plural': 'Sessions Zoom Live',
                'ordering': ['date_session'],
            },
        ),
        migrations.CreateModel(
            name='ContenuPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du contenu pédagogique', max_length=200)),
                ('type_contenu', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier_pdf', models.FileField(blank=True, help_text='Fichier PDF', null=True, upload_to='contenus/pdf/')),
                ('url_video', models.URLField(blank=True, help_text='URL de la vidéo', null=True)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, help_text='Durée en minutes (pour vidéos)', null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus_pedagogiques', to='prepaconcours.matiere')),
            ],
            options={
                'verbose_name': 'Contenu Pédagogique',
                'verbose_name_plural': 'Contenus Pédagogiques',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
