# Generated by Django 4.2.23 on 2025-08-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0020_alter_lecon_options_remove_lecon_date_session_zoom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenupedagogique',
            options={'ordering': ['ordre', 'titre'], 'verbose_name': 'Contenu Pédagogique (Second Tour)', 'verbose_name_plural': 'Contenus Pédagogiques (Second Tour)'},
        ),
        migrations.AlterModelOptions(
            name='lecon',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Leçon (Catégorie - Premier Tour)', 'verbose_name_plural': 'Leçons (Catégories - Premier Tour)'},
        ),
        migrations.AlterModelOptions(
            name='sessionzoomlive',
            options={'ordering': ['date_session'], 'verbose_name': 'Session Zoom Live (Oral)', 'verbose_name_plural': 'Sessions Zoom Live (Oral)'},
        ),
        migrations.AlterField(
            model_name='contenupedagogique',
            name='matiere',
            field=models.ForeignKey(help_text='Matière du second tour ENA (avec cycle)', on_delete=django.db.models.deletion.CASCADE, related_name='contenus_pedagogiques', to='prepaconcours.matiere'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='matiere',
            field=models.ForeignKey(help_text='Matière du premier tour ENA', on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='prepaconcours.matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text='Cycle (uniquement pour second_tour et fonction_publique)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='prepaconcours.cycle'),
        ),
        migrations.AlterField(
            model_name='sessionzoomlive',
            name='matiere',
            field=models.ForeignKey(help_text="Matière de l'oral ENA (sans cycle)", on_delete=django.db.models.deletion.CASCADE, related_name='sessions_zoom', to='prepaconcours.matiere'),
        ),
    ]
