# Generated by Django 4.2.23 on 2025-08-05 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0021_alter_contenupedagogique_options_alter_lecon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temps_total_en_secondes', models.PositiveIntegerField(default=0)),
                ('terminee', models.BooleanField(default=False)),
                ('rang_national', models.PositiveIntegerField(blank=True, help_text='Rang dans le classement national', null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions', models.ManyToManyField(blank=True, related_name='examens_nationaux', to='prepaconcours.question')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_nationaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'temps_total_en_secondes'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrit', models.BooleanField(default=True)),
                ('present', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('examen_national', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prepaconcours.examennational')),
            ],
        ),
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de la session d'examen", max_length=200)),
                ('date_debut', models.DateTimeField(help_text="Date et heure de début de l'examen")),
                ('date_fin', models.DateTimeField(help_text="Date et heure de fin de l'examen")),
                ('duree_minutes', models.PositiveIntegerField(default=180, help_text="Durée de l'examen en minutes (3h par défaut)")),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='programmee', max_length=20)),
                ('nombre_questions', models.PositiveIntegerField(default=100, help_text="Nombre de questions dans l'examen")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('participants', models.ManyToManyField(related_name='sessions_examen', through='prepaconcours.ParticipationExamen', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, related_name='sessions_examen', to='prepaconcours.question')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='participationexamen',
            name='session_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prepaconcours.sessionexamen'),
        ),
        migrations.AddField(
            model_name='participationexamen',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temps_total_en_secondes', models.PositiveIntegerField(default=0)),
                ('terminee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions', models.ManyToManyField(blank=True, related_name='evaluations', to='prepaconcours.question')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='participationexamen',
            unique_together={('utilisateur', 'session_examen')},
        ),
    ]
