# Generated by Django 4.2.7 on 2025-08-14 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0022_examennational_participationexamen_sessionexamen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examennational',
            name='debut_anglais',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examennational',
            name='debut_culture_aptitude',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examennational',
            name='debut_logique_combinee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examennational',
            name='temps_anglais',
            field=models.PositiveIntegerField(default=0, help_text='Temps passé sur Anglais'),
        ),
        migrations.AddField(
            model_name='examennational',
            name='temps_culture_aptitude',
            field=models.PositiveIntegerField(default=0, help_text='Temps passé sur Culture générale + Aptitude verbale'),
        ),
        migrations.AddField(
            model_name='examennational',
            name='temps_logique_combinee',
            field=models.PositiveIntegerField(default=0, help_text="Temps passé sur Logique d'organisation + Logique numérique"),
        ),
        migrations.CreateModel(
            name='QuestionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_question', models.CharField(help_text='Code unique de la question (ex: ENA2024-CG-001)', max_length=20, unique=True)),
                ('texte', models.TextField(help_text='Énoncé de la question')),
                ('type_question', models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('vrai_faux', 'Vrai/Faux'), ('texte_court', 'Texte court'), ('texte_long', 'Texte long')], default='choix_unique', max_length=20)),
                ('matiere_combinee', models.CharField(choices=[('culture_aptitude', 'Culture générale et Aptitude verbale'), ('logique_combinee', "Logique d'organisation et Logique numérique"), ('anglais', 'Anglais')], help_text="Matière combinée de l'examen national", max_length=20)),
                ('choix_a', models.TextField(blank=True, help_text='Choix A (pour QCM)', null=True)),
                ('choix_b', models.TextField(blank=True, help_text='Choix B (pour QCM)', null=True)),
                ('choix_c', models.TextField(blank=True, help_text='Choix C (pour QCM)', null=True)),
                ('choix_d', models.TextField(blank=True, help_text='Choix D (pour QCM)', null=True)),
                ('choix_e', models.TextField(blank=True, help_text='Choix E (optionnel)', null=True)),
                ('bonne_reponse', models.CharField(blank=True, help_text='Bonne(s) réponse(s) pour QCM (ex: A, AB, VRAI)', max_length=10, null=True)),
                ('reponse_attendue', models.TextField(blank=True, help_text='Réponse attendue pour questions texte', null=True)),
                ('correction_mode', models.CharField(choices=[('exacte', 'Exacte'), ('mot_cle', 'Mot-clé'), ('regex', 'Regex')], default='exacte', help_text='Mode de correction pour questions texte', max_length=10)),
                ('explication', models.TextField(blank=True, help_text='Explication de la réponse', null=True)),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=10)),
                ('temps_limite_secondes', models.PositiveIntegerField(default=120, help_text='Temps limite en secondes pour cette question')),
                ('active', models.BooleanField(default=True, help_text='Question active pour les examens')),
                ('validee', models.BooleanField(default=False, help_text='Question validée par un administrateur')),
                ('nombre_utilisations', models.PositiveIntegerField(default=0, help_text='Nombre de fois utilisée dans des examens')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('creee_par', models.CharField(blank=True, help_text='Créateur de la question', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Question Examen National',
                'verbose_name_plural': 'Questions Examen National',
                'ordering': ['matiere_combinee', 'code_question'],
                'indexes': [models.Index(fields=['matiere_combinee', 'active'], name='prepaconcou_matiere_ea9e8c_idx'), models.Index(fields=['type_question', 'difficulte'], name='prepaconcou_type_qu_225916_idx'), models.Index(fields=['validee', 'active'], name='prepaconcou_validee_153c0d_idx')],
            },
        ),
        migrations.AlterField(
            model_name='examennational',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='examens_nationaux', to='prepaconcours.questionexamen'),
        ),
    ]
