# Generated by Django 4.2.7 on 2025-08-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0023_examennational_debut_anglais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='matiere_examen_national',
            field=models.CharField(blank=True, choices=[('culture_aptitude', 'Culture générale + Aptitude verbale'), ('logique_combinee', 'Logique + Raisonnement'), ('anglais', 'Anglais')], help_text="Matière combinée pour l'examen national", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='choix_concours',
            field=models.CharField(choices=[('ENA', 'ENA'), ('fonction_publique', 'Fonction Publique'), ('examen_national', 'Examen National')], default='ENA', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='choix_concours',
            field=models.CharField(choices=[('ENA', 'ENA'), ('fonction_publique', 'Fonction Publique'), ('examen_national', 'Examen National')], default='ENA', max_length=32),
        ),
        migrations.AlterField(
            model_name='tentative',
            name='choix_concours',
            field=models.CharField(choices=[('ENA', 'ENA'), ('fonction_publique', 'Fonction Publique'), ('examen_national', 'Examen National')], default='ENA', max_length=32),
        ),
    ]
