# Generated by Django 4.2.7 on 2025-08-16 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0024_matiere_matiere_examen_national_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_donnee', models.TextField(blank=True)),
                ('est_correcte', models.BooleanField(default=False)),
                ('temps_reponse', models.IntegerField(default=0, help_text='Temps de réponse en secondes')),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere_combinee', models.CharField(choices=[('culture_aptitude', 'Culture générale + Aptitude verbale'), ('logique_combinee', 'Logique + Raisonnement'), ('anglais', 'Anglais')], max_length=20)),
                ('type_session', models.CharField(choices=[('composition', 'Composition Nationale'), ('entrainement', 'Entraînement')], default='composition', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_prevue', models.IntegerField(help_text='Durée prévue en minutes')),
                ('est_terminee', models.BooleanField(default=False)),
                ('score_final', models.FloatField(blank=True, null=True)),
                ('nombre_bonnes_reponses', models.IntegerField(default=0)),
                ('nombre_total_questions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterModelOptions(
            name='questionexamen',
            options={'ordering': ['matiere__nom', 'lecon__nom', 'code_question'], 'verbose_name': 'Question Examen National', 'verbose_name_plural': 'Questions Examen National'},
        ),
        migrations.RemoveIndex(
            model_name='questionexamen',
            name='prepaconcou_matiere_ea9e8c_idx',
        ),
        migrations.RemoveField(
            model_name='questionexamen',
            name='creee_par',
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='lecon',
            field=models.ForeignKey(blank=True, help_text='Leçon spécifique (optionnelle, pour organiser les questions par thème)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_examen', to='prepaconcours.lecon'),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='matiere',
            field=models.ForeignKey(blank=True, help_text="Matière de l'examen national (choix_concours='examen_national')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_examen', to='prepaconcours.matiere'),
        ),
        migrations.AlterField(
            model_name='questionexamen',
            name='matiere_combinee',
            field=models.CharField(blank=True, help_text='Matière combinée (calculée automatiquement depuis matiere.matiere_examen_national)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='questionexamen',
            index=models.Index(fields=['matiere', 'active'], name='prepaconcou_matiere_dfafd4_idx'),
        ),
        migrations.AddField(
            model_name='sessioncomposition',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_composition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reponsecomposition',
            name='question_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prepaconcours.questionexamen'),
        ),
        migrations.AddField(
            model_name='reponsecomposition',
            name='session_composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_composition', to='prepaconcours.sessioncomposition'),
        ),
        migrations.AlterUniqueTogether(
            name='reponsecomposition',
            unique_together={('session_composition', 'question_examen')},
        ),
    ]
