# Generated by Django 4.2.7 on 2025-08-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0025_reponsecomposition_sessioncomposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoixExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_choix', models.TextField(help_text='Texte du choix de réponse')),
                ('est_correcte', models.BooleanField(default=False, help_text='Ce choix est-il correct ?')),
                ('ordre', models.PositiveIntegerField(default=1, help_text="Ordre d'affichage du choix")),
                ('question_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_examen', to='prepaconcours.questionexamen')),
            ],
            options={
                'verbose_name': "Choix d'examen",
                'verbose_name_plural': "Choix d'examens",
                'ordering': ['ordre'],
            },
        ),
    ]
