# Generated by Django 4.2.7 on 2025-08-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0026_choixexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenupedagogique',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='ID de la vidéo YouTube (ex: dQw4w9WgXcQ)', max_length=50, null=True),
        ),
    ]
