# Generated by Django 4.2.27 on 2026-01-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0027_contenupedagogique_youtube_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenupedagogique',
            name='active',
            field=models.BooleanField(default=True, help_text='Automatiquement activé à la création'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='active',
            field=models.BooleanField(default=True, help_text='Automatiquement activé à la création'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='auth_provider',
            field=models.CharField(default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prepaconcours.cycle'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='prepaconcours_utilisateur',
        ),
    ]
