# Generated by Django 4.2.27 on 2026-01-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0028_alter_contenupedagogique_active_alter_lecon_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Image de la question encodée en base64 (pour les questions de logique)', null=True),
        ),
    ]
