# Generated by Django 4.2.27 on 2026-01-16 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0029_question_image_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé'), ('en_attente', 'En attente de paiement')], default='en_attente', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('test', 'Test'), ('basique', 'Basique'), ('premium', 'Premium'), ('annuel', 'Annuel')], max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.IntegerField(help_text='Prix en FCFA')),
                ('duree', models.CharField(choices=[('24h', '24 heures'), ('1_mois', '1 mois'), ('12_mois', '12 mois')], max_length=20)),
                ('questions_par_jour', models.IntegerField(default=0, help_text='0 = illimité')),
                ('examens_blancs_par_mois', models.IntegerField(default=0, help_text='0 = illimité')),
                ('acces_ena', models.BooleanField(default=True)),
                ('acces_fonction_publique', models.BooleanField(default=False)),
                ('acces_tous_concours', models.BooleanField(default=False)),
                ('mode_classique', models.BooleanField(default=True)),
                ('mode_chronometre', models.BooleanField(default=False)),
                ('statistiques_basiques', models.BooleanField(default=False)),
                ('statistiques_avancees', models.BooleanField(default=False)),
                ('corrections_detaillees', models.BooleanField(default=False)),
                ('support_email', models.BooleanField(default=False)),
                ('support_prioritaire', models.BooleanField(default=False)),
                ('support_vip', models.BooleanField(default=False)),
                ('export_pdf', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_populaire', models.BooleanField(default=False, help_text="Afficher le badge 'Populaire'")),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='ID unique de la transaction', max_length=100, unique=True)),
                ('cinetpay_transaction_id', models.CharField(blank=True, help_text='ID CinetPay', max_length=100, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('montant', models.IntegerField(help_text='Montant en FCFA')),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('methode_paiement', models.CharField(blank=True, help_text='Mobile Money, Carte, etc.', max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('cinetpay_response', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='prepaconcours.abonnement')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='prepaconcours.plan')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='abonnement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='prepaconcours.plan'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuotaUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('questions_utilisees', models.IntegerField(default=0)),
                ('examens_blancs_utilises', models.IntegerField(default=0)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas_utilisation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('utilisateur', 'date')},
            },
        ),
    ]
