# Generated by Django 4.2.27 on 2026-01-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0030_abonnement_plan_transaction_abonnement_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecon',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Leçon (Catégorie ENA)', 'verbose_name_plural': 'Leçons (Catégories ENA)'},
        ),
        migrations.AlterUniqueTogether(
            name='lecon',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lecon',
            name='type_lecon',
            field=models.CharField(choices=[('quiz', 'Quiz ENA'), ('evaluation', 'Évaluation ENA')], default='quiz', help_text='Type de leçon: quiz ou évaluation', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='matiere',
            field=models.ForeignKey(help_text='Matière ENA (premier tour)', on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='prepaconcours.matiere'),
        ),
        migrations.AlterUniqueTogether(
            name='lecon',
            unique_together={('nom', 'matiere', 'type_lecon')},
        ),
    ]
