# Generated by Django 4.2.27 on 2026-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0031_add_type_lecon_to_lecon'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_source',
            field=models.CharField(choices=[('quiz', 'Quiz ENA'), ('evaluation', 'Évaluation ENA')], default='quiz', help_text='Type de source: quiz ou évaluation', max_length=20),
        ),
    ]
