# Generated by Django 4.2.27 on 2026-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0033_migrate_evaluation_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere_combinee', models.CharField(choices=[('culture_aptitude', 'Culture générale + Aptitude verbale'), ('anglais', 'Anglais'), ('logique_combinee', "Logique d'organisation + Logique numérique")], max_length=30, unique=True)),
                ('titre_principal', models.CharField(default='FEUILLE DE COMPOSITION', max_length=200)),
                ('sous_titre_1', models.CharField(default="CONCOURS DIRECT D'ENTRÉE EN 2024", max_length=200)),
                ('sous_titre_2', models.CharField(default="AU CYCLE MOYEN DE L'ENA", max_length=200)),
                ('nom_affichage', models.CharField(help_text='Nom affiché sur la page (ex: Culture générale + Aptitude verbale)', max_length=200)),
                ('duree_minutes', models.IntegerField(default=90, help_text='Durée en minutes')),
                ('nombre_questions', models.IntegerField(default=40, help_text='Nombre de questions')),
                ('instruction_principale', models.TextField(default='Choisissez la bonne réponse parmi les quatre propositions.', help_text='Instruction principale affichée')),
                ('bareme_bonne_reponse', models.DecimalField(decimal_places=2, default=0.5, help_text='Points pour une bonne réponse', max_digits=4)),
                ('bareme_mauvaise_reponse', models.DecimalField(decimal_places=2, default=-0.25, help_text='Points pour une mauvaise réponse', max_digits=4)),
                ('bareme_absence_reponse', models.DecimalField(decimal_places=2, default=0, help_text='Points pour absence de réponse', max_digits=4)),
                ('couleur_primaire', models.CharField(default='#667eea', help_text='Code couleur hex (ex: #667eea)', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#764ba2', help_text='Code couleur hex secondaire', max_length=7)),
                ('message_intro', models.TextField(default='Cliquez sur "Commencer" pour démarrer le timer et commencer la composition.', help_text='Message affiché avant de commencer')),
                ('bouton_commencer', models.CharField(default='Commencer la composition', max_length=100)),
                ('bouton_terminer', models.CharField(default='Terminer la composition', max_length=100)),
                ('pied_de_page', models.TextField(blank=True, help_text='Texte du pied de page (optionnel)')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Composition',
                'verbose_name_plural': 'Configurations Compositions',
                'ordering': ['matiere_combinee'],
            },
        ),
    ]
