# Generated by Django 4.2.27 on 2026-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaconcours', '0035_create_default_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionexamen',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Image de la question en base64 (pour schémas, diagrammes)', null=True),
        ),
    ]
